### PR TITLE
Documentation(EJ2-58558): Added Documentation for the Adaptive View Feature

### PR DESCRIPTION
**Pull request by BalajiElumalai99**
### Document description
1) Running the Treegrid component in the adaptive layout. We can use the treegrid component in the mobile or desktop using the adaptive layout feature.
2) Added the sample to run and gave details about the feature.
3) Given property links to know the details about the property with their usage description.

### CODE REVIEW

**Review by thavasianand — APPROVED** [review]
fix is fine

**Review by thavasianand — APPROVED** [review]
Fix is fine

**Review by thavasianand — APPROVED** [review]
fix is fine

**Comment by laksmipriyamurugesan** [comment]
Reviewed the content

**Review by thavasianand — APPROVED** [review]
fix is fine

**Review by thavasianand — APPROVED** [review]
fix is fine

**Review by thavasianand — APPROVED** [review]
fix is fine

**Pull request merged**
