### PR TITLE
IN-18783: Check font weight of body content-dev

### PR DESCRIPTION
**Pull request by SriramThangaraj**
| Title | Description |
| -------- | -------- |
|**Task Link**|https://syncfusion.atlassian.net/browse/IN-18783|
|**Analysis and design**|1. Analyzed the details in the task.<br/>2. No design changes are required.|
|**Solution description**|1.Added the font weight in the controlcategory class.<br> 2.Set the font weight to 500|
|**Output screenshots**|-|
|**Areas affected and ensured**|<ul><li>Changes in the ASP .Net Core and MVC introduction.md. Previous code didn't affected and ensured in end.</li></ul>|
|**Test cases**|Check the site locally.|
|**Testbed sample location**|-|
|**Additional CheckList**|<ul><li>Did you run the automation against your fix? No</li><li>Is there any API name change?No</li><li>Is there any existing behavior change of other features due to this code change? No.</li><li>Does your new code introduce new warnings or binding errors? No.</li><li>Does your code pass all FxCop and StyleCop rules? Yes.</li><li> Did you record this case in the unit test or UI test? N/A</li></ul>|

### CODE REVIEW

**Comment by SriramThangaraj** [comment]
rebuild

**Comment by SriramThangaraj** [comment]
rebuild

**Comment by SriramThangaraj** [comment]
rebuild

**Comment by SriramThangaraj** [comment]
rebuild

**Review by Poovarasan-Karthikeyan — APPROVED** [review]

**Pull request merged**
