### PR TITLE
documentation(EJ2-63143): Added Getting Started Documentation for the mention in ASPNet Core & MVC platforms.

### PR DESCRIPTION
**Pull request by IndrajithSrinivasan**
documentation(EJ2-63143): Added Getting Started Documentation for the mention in ASPNet Core & MVC platforms.

### CODE REVIEW

**Comment by IndrajithSrinivasan** [comment]
rebuild

**Comment by IndrajithSrinivasan** [comment]
rebuild

**Comment by IndrajithSrinivasan** [comment]
rebuild

**Comment by IndrajithSrinivasan** [comment]
rebuild

**Comment by IndrajithSrinivasan** [comment]
rebuild

**Comment by IndrajithSrinivasan** [comment]
rebuild

**Comment by IndrajithSrinivasan** [comment]
rebuild

**Review by thangavele — APPROVED** [review]

**Pull request merged**
