### PR TITLE
documentation(EJ2-66586): To clear the broken links issue in the UG documentation

### PR DESCRIPTION
**Pull request by sangeetha-priya-M**
Feature description
Need to clear the broken links issue in the UG documentation

Analysis and design
Cleared the broken links issue in the UG documentation

Solution description
Clear the broken links issue in the UG documentation

Output Screenshot
NA

Areas affected and ensured
NA

Test cases
NA

### CODE REVIEW

**Comment by sangeetha-priya-M** [comment]
rebuild

**Comment by sangeetha-priya-M** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Comment by sangeetha-priya-M** [comment]
rebuild

**Comment by sangeetha-priya-M** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Comment by sangeetha-priya-M** [comment]
rebuild

**Review by gobalakrishnans — APPROVED** [review]

**Pull request merged**
