### PR TITLE
documentation(EJ2CORE-724): ASP.NET Core UG common changes committed.

### PR DESCRIPTION
**Pull request by Balaji-Elumalai**
ASP.NET Core UG common changes committed.

### CODE REVIEW

**Comment by Balaji-Elumalai** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Comment by Balaji-Elumalai** [comment]
rebuild

**Review by rajendranr-5483 — APPROVED** [review]

**Pull request merged**
