### PR TITLE
documentation(EJ2-58712): UG topic for set the label color based on series color in chart.

### PR DESCRIPTION
**Pull request by Praveenkumar-N**
UG topic for set the label color based on series color in chart.

### CODE REVIEW

**Comment by Praveenkumar-N** [comment]
rebuild

**Comment by Praveenkumar-N** [comment]
rebuild

**Comment by syncsiva** [comment]
rebuild

**Comment by syncsiva** [comment]
rebuild

**Review by syncsiva — APPROVED** [review]

**Pull request merged**
