### PR TITLE
EJ2-57882 Reviewed the contents in EJ2 Core

### PR DESCRIPTION
**Pull request by IshwariyaGuru**
Reviewed the contents

### CODE REVIEW

**Comment by IshwariyaGuru** [comment]
rebuild

**Comment by IshwariyaGuru** [comment]
rebuild

**Comment by IshwariyaGuru** [comment]
rebuild

**Comment by Backiaraj** [comment]
rebuild

**Comment by Backiaraj** [comment]
rebuild

**Comment by IshwariyaGuru** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Review by syncsiva — APPROVED** [review]

**Pull request merged**
