### PR TITLE
documentation(EJ2-60487): UG topic for prevent row re-ordering has in gantt has been added.

### PR DESCRIPTION
**Pull request by Praveenkumar-N**
UG topic for prevent row re-ordering has in gantt has been added.

### CODE REVIEW

**Comment by Praveenkumar-N** [comment]
rebuild

**Comment by Praveenkumar-N** [comment]
rebuild

**Comment by Praveenkumar-N** [comment]
rebuild

**Comment by syncsiva** [comment]
rebuild

**Comment by Manikandan-Lakshmanan** [comment]
rebuild

**Comment by Manikandan-Lakshmanan** [comment]
rebuild

**Review by syncsiva — APPROVED** [review]

**Pull request merged**
