### PR TITLE
documentation(EJ2-62129):Improvement in JawsReader-Accessibility

### PR DESCRIPTION
**Pull request by Aishwarya-SF3446**
CssClass added for Jaws reader

### CODE REVIEW

**Comment by Aishwarya-SF3446** [comment]
Rebuild

**Comment by Aishwarya-SF3446** [comment]
Rebuild

**Comment by Aishwarya-SF3446** [comment]
Rebuild

**Comment by Aishwarya-SF3446** [comment]
Rebuild

**Comment by Aishwarya-SF3446** [comment]
Rebuild

**Review by jmfarook7 — APPROVED** [review]
fine

**Pull request merged**
