### PR TITLE
documentation(EJ2-67364): Added UG for lazy loading, load child ondemand with virtualization and Shimmer effect in remote data binding feature

### PR DESCRIPTION
**Pull request by Priyadarshan97**
Added UG for lazy loading, load child ondemand with virtualization and Shimmer effect in remote data binding feature.

### CODE REVIEW

**Review by thavasianand — APPROVED** [review]
changes are fine

**Comment by Priyadarshan97** [comment]
rebuild

**Comment by Priyadarshan97** [comment]
rebuild

**Review by thavasianand — APPROVED** [review]
changes are fine

**Comment by Priyadarshan97** [comment]
rebuild

**Pull request closed without merging**
