### PR TITLE
EJ2CORE-747-Modified getting started document for ASPNET.Core ContextMenu, DashboardLayout, DatePicker, DateRangePicker and DateTimePicker controls

### PR DESCRIPTION
**Pull request by Backiaraj**

### CODE REVIEW

**Review by rajendranr-5483 — APPROVED** [review]

**Comment by Backiaraj** [comment]
rebuild

**Comment by Backiaraj** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Pull request closed without merging**
