### PR TITLE
documentation(EJ2CORE-888): conflict resolved.

### PR DESCRIPTION
**Pull request by SF3884-Shanmugarajan**
### Feature description
Need to update position topic for Fab control UG documentation.

### Analysis and design
Update position topic for Fab control UG documentation.

### Solution description
Updated position topic for Fab control UG documentation.

### Areas affected and ensured

None (New Component)
 
### Test cases

NA

### Test bed sample location

NA
 
### Additional checklist

* Did you run the automation against your implementation? NA
* Is there any API name change? Yes.
* Is there any existing behavior change of other features due to this code change? No
* Does your new code introduce new warnings or binding errors? No
* Does your code pass all FxCop and StyleCop rules? Yes
* Did you record this case in the unit test or UI test? Yes

### CODE REVIEW

**Comment by SF3884-Shanmugarajan** [comment]
rebuild

**Comment by SF3884-Shanmugarajan** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Comment by DeepakRajSundar** [comment]
rebuild

**Review by silambarasani — APPROVED** [review]

**Pull request merged**
