### PR TITLE
SEO-187689-EJ2-ASP.NET-CORE-introduction--Page-with-redirect-links

### PR DESCRIPTION
**Pull request by Faith-Atieno**
Title | Description
-- | --
|Task Category | Coverage Issues page with redirect links|
|Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/3380|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187689/|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/doc.aspx?sourcedoc=%7B784f2f7f-0d42-48b0-902e-7ec68a4dec10%7D&action=edit|

Changes Made | Reason for change |
|-- | -- |
|Changed redirect links | To avoid redirection 301 or 302 links, providing direct links. |

### CODE REVIEW

**Comment by Faith-Atieno** [comment]
rebuild

**Comment by Faith-Atieno** [comment]
rebuild

**Review by Yvone-Atieno — APPROVED** [review]
Approved

**Review by Aishwarya-Ganesan — APPROVED** [review]
fine.

**Pull request merged**
